// Mocks generated by Mockito 5.4.6 from annotations
// in fitnflaifrontendv2/test/providers/specialist_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:fitnflaifrontendv2/models/credit_card.dart' as _i6;
import 'package:fitnflaifrontendv2/models/specialist.dart' as _i8;
import 'package:fitnflaifrontendv2/models/turno.dart' as _i9;
import 'package:fitnflaifrontendv2/services/payments_service.dart' as _i3;
import 'package:fitnflaifrontendv2/services/specialist_service.dart' as _i7;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentsService extends _i1.Mock implements _i3.PaymentsService {
  MockPaymentsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> initPayment(
    String? token,
    String? priceId,
    String? returnUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initPayment, [token, priceId, returnUrl]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#initPayment, [token, priceId, returnUrl]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> initPaymentMeetingSpecialist(
    String? token,
    int? trackingId,
    String? returnUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initPaymentMeetingSpecialist, [
              token,
              trackingId,
              returnUrl,
            ]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#initPaymentMeetingSpecialist, [
                  token,
                  trackingId,
                  returnUrl,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> initAddCard(String? token, String? returnUrl) =>
      (super.noSuchMethod(
            Invocation.method(#initAddCard, [token, returnUrl]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#initAddCard, [token, returnUrl]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> saveCard(
    String? token,
    String? userId,
    Map<String, dynamic>? cardData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCard, [token, userId, cardData]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.CreditCard>> getSavedCards(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSavedCards, [token]),
            returnValue: _i4.Future<List<_i6.CreditCard>>.value(
              <_i6.CreditCard>[],
            ),
          )
          as _i4.Future<List<_i6.CreditCard>>);

  @override
  _i4.Future<void> deleteCard(String? token, String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [token, cardId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<dynamic> subscribeNuvei(
    String? token,
    String? priceId, {
    String? cvc = '123',
    String? deviceType = 'mobile',
    String? referenceId,
    String? ip = '127.0.0.1',
    String? language = 'es',
    bool? javaEnabled = true,
    bool? jsEnabled = true,
    int? colorDepth = 24,
    int? screenHeight = 1080,
    int? screenWidth = 1920,
    int? timezoneOffset = 0,
    String? userAgent =
        'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1',
    String? acceptHeader = 'application/json',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeNuvei,
              [token, priceId],
              {
                #cvc: cvc,
                #deviceType: deviceType,
                #referenceId: referenceId,
                #ip: ip,
                #language: language,
                #javaEnabled: javaEnabled,
                #jsEnabled: jsEnabled,
                #colorDepth: colorDepth,
                #screenHeight: screenHeight,
                #screenWidth: screenWidth,
                #timezoneOffset: timezoneOffset,
                #userAgent: userAgent,
                #acceptHeader: acceptHeader,
              },
            ),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> chargeWithSavedCard(
    String? token,
    String? priceId,
    String? cardId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#chargeWithSavedCard, [token, priceId, cardId]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> payMeetingSpecialistOneClick(
    String? token,
    int? trackingId, {
    String? cvc = '123',
    Map<String, dynamic>? extraData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #payMeetingSpecialistOneClick,
              [token, trackingId],
              {#cvc: cvc, #extraData: extraData},
            ),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> refundNuvei(
    String? token,
    String? reference,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refundNuvei, [token, reference, reason]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getPlanes(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanes, [token]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> simulatePurchase(String? token, String? priceId) =>
      (super.noSuchMethod(
            Invocation.method(#simulatePurchase, [token, priceId]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<String> getStatus(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, [token]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getStatus, [token]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<dynamic> changePlan(String? token, String? priceId) =>
      (super.noSuchMethod(
            Invocation.method(#changePlan, [token, priceId]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> startFreeTrial(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#startFreeTrial, [token]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}

/// A class which mocks [SpecialistService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpecialistService extends _i1.Mock implements _i7.SpecialistService {
  MockSpecialistService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
          )
          as _i2.Client);

  @override
  _i4.Future<List<_i8.Specialist>> getSpecialists(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecialists, [token]),
            returnValue: _i4.Future<List<_i8.Specialist>>.value(
              <_i8.Specialist>[],
            ),
          )
          as _i4.Future<List<_i8.Specialist>>);

  @override
  _i4.Future<Map<String, dynamic>> solicitarCita(
    String? token, {
    required int? idEspecialista,
    int? idSeguimiento,
    required String? fechaHora,
    required bool? esExpress,
    required String? descripcionCita,
    required String? tipoCita,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #solicitarCita,
              [token],
              {
                #idEspecialista: idEspecialista,
                #idSeguimiento: idSeguimiento,
                #fechaHora: fechaHora,
                #esExpress: esExpress,
                #descripcionCita: descripcionCita,
                #tipoCita: tipoCita,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> requestSpecialistTracking(
    String? token,
    int? specialistId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestSpecialistTracking, [
              token,
              specialistId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Turno>> getSpecialistAvailability(
    String? token,
    String? fechaInicio,
    String? fechaFin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpecialistAvailability, [
              token,
              fechaInicio,
              fechaFin,
            ]),
            returnValue: _i4.Future<List<_i9.Turno>>.value(<_i9.Turno>[]),
          )
          as _i4.Future<List<_i9.Turno>>);

  @override
  _i4.Future<String> generarReportePDF(String? token, String? idReporte) =>
      (super.noSuchMethod(
            Invocation.method(#generarReportePDF, [token, idReporte]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generarReportePDF, [token, idReporte]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> getAssignedSpecialistInfo(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getAssignedSpecialistInfo, [token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> cancelarCita(
    String? token, {
    required int? idCita,
    required String? motivoCancelacion,
    String? canceladoPor = 'usuario',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cancelarCita,
              [token],
              {
                #idCita: idCita,
                #motivoCancelacion: motivoCancelacion,
                #canceladoPor: canceladoPor,
              },
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
