# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends usage stats which we don't need
# install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Forzamos que todos los pods compilen apuntando a iOS 14.0 como mínimo
      # Esto resuelve problemas de visibilidad de APIs modernas (como isiOSAppOnVision en device_info_plus) en Xcode 15/16
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
